//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maraton
    {
        public Maraton()
        {
            this.ResultadoMaratonParticipantes = new HashSet<ResultadoMaratonParticipante>();
        }
    
        public int IdMaraton { get; set; }
        public string Nombre { get; set; }
        public int MaxParticipantes { get; set; }
        public string LugarSalida { get; set; }
        public int ParticipantesEnEspera { get; set; }
        public int PrimerPremio { get; set; }
        public int SegundoPremio { get; set; }
        public int TercerPremio { get; set; }
        public Nullable<System.DateTime> FechaHorarioComienzo { get; set; }
    
        public virtual ICollection<ResultadoMaratonParticipante> ResultadoMaratonParticipantes { get; set; }
    }
}
